INSERT INTO products (
    name, description, category, subcategory, brand, sku, price, stock_quantity, is_active, images, tags, variants
) VALUES
-- --- Electronics (1-10) ---
(
    'Quantum Leap Laptop 14 Pro',
    'High-performance laptop with M10 chip, ideal for coding and graphic design. Sleek aluminum unibody.',
    'Electronics',
    'Laptops',
    'TechNova',
    'TN-LP-QL14P',
    1999.99,
    15,
    TRUE,
    '{"laptop_1.jpg"}', -- Images
    '{"high-end", "m10", "ultrabook", "gaming"}', -- Tags
    '{"storage":["512GB SSD","1TB SSD"], "ram":["16GB","32GB"]}' -- Variants
),
(
    'Aura Noise-Cancelling Headphones',
    'Exceptional sound quality with industry-leading noise cancellation. 50 hours battery life.',
    'Electronics',
    'Audio',
    'SoundStream',
    'SS-HP-ANC-AURA',
    249.00,
    50,
    TRUE,
    '{"headphone_1.jpg"}',
    '{"wireless", "bluetooth", "bass", "travel"}',
    '{"color":["Midnight Black","Space Grey","Cosmic Blue"]}'
),
(
    'Chrono Smartwatch X9',
    'Fitness tracking, heart rate monitor, and built-in GPS. Waterproof design with always-on display.',
    'Electronics',
    'Wearables',
    'ChronoTech',
    'CT-SW-X9',
    179.50,
    120,
    TRUE,
    '{"smartwatch_1.jpg"}',
    '{"gps", "waterproof", "fitness", "android"}',
    '{"band_size":["S/M","M/L"], "band_color":["Black Silicone","White Leather"]}'
),
(
    'Nova 8K QLED TV 65"',
    'Stunning 8K resolution with deep blacks and vibrant colors. Smart TV capabilities.',
    'Electronics',
    'TVs',
    'ViewMax',
    'VM-TV-8K-65',
    3499.00,
    5,
    TRUE,
    '{"tv_1.jpg"}',
    '{"8k", "qled", "smart-tv", "cinema"}',
    '{}'
),
(
    'Power Surge 20000mAh Power Bank',
    'Fast charging portable charger for multiple devices. Slim and lightweight design.',
    'Electronics',
    'Accessories',
    'ChargeMax',
    'CM-PB-20K',
    35.99,
    300,
    TRUE,
    '{"powerbank_1.jpg"}',
    '{"portable", "fast-charge", "usb-c"}',
    '{"color":["Black","Red"]}'
),
(
    'Gaming Mechanical Keyboard V2',
    'Tactile brown switches with customizable RGB lighting. Full anti-ghosting.',
    'Electronics',
    'Gaming',
    'GamerGear',
    'GG-KB-MECV2',
    119.99,
    80,
    TRUE,
    '{"keyboard_1.jpg"}',
    '{"mechanical", "rgb", "pc-gaming", "esports"}',
    '{"switch_type":["Brown","Red","Blue"]}'
),
(
    'HD Webcam 1080p Streamer Edition',
    'Crystal clear 1080p resolution at 60fps, perfect for streaming and video conferencing.',
    'Electronics',
    'PC Peripherals',
    'ClearView',
    'CV-WC-1080S',
    45.00,
    150,
    TRUE,
    '{"webcam_1.jpg"}',
    '{"streaming", "webcam", "video-call"}',
    '{}'
),
(
    'Mesh Wi-Fi System Tri-Band',
    'Eliminate dead zones with seamless tri-band mesh technology. Easy setup.',
    'Electronics',
    'Networking',
    'NetSwift',
    'NS-MWF-TB',
    199.00,
    40,
    TRUE,
    '{"wifi_1.jpg"}',
    '{"mesh", "tri-band", "router", "home-network"}',
    '{}'
),
(
    'E-Reader 7" Paperwhite Display',
    'Glare-free screen and adjustable warm light for comfortable reading.',
    'Electronics',
    'E-Readers',
    'BookSmart',
    'BS-ER-7PW',
    129.99,
    60,
    TRUE,
    '{"ereader_1.jpg"}',
    '{"ebook", "reading", "paperwhite"}',
    '{"storage":["8GB","32GB"]}'
),
(
    'Portable Bluetooth Speaker X-Bass',
    'Powerful bass and rugged, waterproof design. Perfect for outdoor parties.',
    'Electronics',
    'Audio',
    'SoundStream',
    'SS-SP-XB',
    65.00,
    100,
    TRUE,
    '{"speaker_1.jpg"}',
    '{"bluetooth", "waterproof", "portable", "bass"}',
    '{"color":["Black","Olive Green","Desert Tan"]}'
),
-- --- Clothing & Apparel (11-20) ---
(
    'Urban Explorer Denim Jacket',
    'Classic fit denim jacket with light distressing. 100% cotton.',
    'Apparel',
    'Outerwear',
    'StitchLine',
    'SL-JA-DENIM',
    85.00,
    45,
    TRUE,
    '{"denim_jacket_1.jpg"}',
    '{"denim", "jacket", "casual", "mens"}',
    '{"color":["Light Wash","Dark Wash"], "size":["S","M","L","XL"]}'
),
(
    'Aero-Knit Performance T-Shirt',
    'Moisture-wicking fabric for intense workouts. Reflective logo.',
    'Apparel',
    'Activewear',
    'FlexFit',
    'FF-TS-AERO',
    29.99,
    200,
    TRUE,
    '{"tshirt_1.jpg"}',
    '{"gym", "running", "moisture-wicking", "womens"}',
    '{"color":["Black","Neon Green","Coral"], "size":["XS","S","M","L"]}'
),
(
    'The Essential Leather Wallet',
    'Minimalist genuine leather bifold wallet with RFID protection.',
    'Apparel',
    'Accessories',
    'LeatherCraft',
    'LC-WA-ESNT',
    49.50,
    150,
    TRUE,
    '{"wallet_1.jpg"}',
    '{"leather", "rfid", "bifold", "minimalist"}',
    '{"color":["Brown","Black"]}'
),
(
    'High-Waist Yoga Leggings',
    'Ultra-soft stretch fabric with deep side pockets. Perfect for yoga and leisure.',
    'Apparel',
    'Activewear',
    'FlexFit',
    'FF-LG-YOGA',
    45.00,
    180,
    TRUE,
    '{"leggings_1.jpg"}',
    '{"yoga", "high-waist", "stretch", "womens"}',
    '{"color":["Navy","Charcoal Grey"], "size":["XS","S","M","L"]}'
),
(
    'Classic Wool Scarf',
    'Soft and warm 100% wool scarf. Unisex design.',
    'Apparel',
    'Accessories',
    'WinterWarmth',
    'WW-SC-WOOL',
    39.00,
    90,
    TRUE,
    '{"scarf_1.jpg"}',
    '{"wool", "winter", "unisex", "gift"}',
    '{"color":["Red Plaid","Grey Herringbone"]}'
),
(
    'Vintage Wash Cotton Hoodie',
    'Heavyweight cotton hoodie with a faded, vintage look.',
    'Apparel',
    'Casualwear',
    'StitchLine',
    'SL-HD-VINT',
    65.00,
    70,
    TRUE,
    '{"hoodie_1.jpg"}',
    '{"cotton", "hoodie", "oversized", "unisex"}',
    '{"color":["Stone","Forest Green"], "size":["M","L","XL"]}'
),
(
    'Silky Nightwear Set',
    'Two-piece silky satin nightwear set for maximum comfort.',
    'Apparel',
    'Sleepwear',
    'DreamWeave',
    'DW-NW-SILK',
    55.99,
    110,
    TRUE,
    '{"nightwear_1.jpg"}',
    '{"satin", "sleep", "luxury", "womens"}',
    '{"color":["Burgundy","Champagne"], "size":["S","M","L"]}'
),
(
    'Leather Ankle Boots',
    'Handcrafted genuine leather ankle boots with sturdy sole.',
    'Apparel',
    'Footwear',
    'FootSense',
    'FS-BT-ANKL',
    125.00,
    55,
    TRUE,
    '{"boots_1.jpg"}',
    '{"leather", "boots", "winter", "mens"}',
    '{"color":["Black","Dark Brown"], "size":["8","9","10","11"]}'
),
(
    'Beanie Hat Recycled Yarn',
    'Warm ribbed beanie made from recycled materials.',
    'Apparel',
    'Accessories',
    'WinterWarmth',
    'WW-BH-RECY',
    19.99,
    180,
    TRUE,
    '{"beanie_1.jpg"}',
    '{"beanie", "recycled", "eco-friendly", "winter"}',
    '{"color":["Navy","Mustard","Beige"]}'
),
(
    'Cargo Style Joggers',
    'Comfortable cotton joggers with multiple utility pockets.',
    'Apparel',
    'Casualwear',
    'FlexFit',
    'FF-JG-CARG',
    59.00,
    95,
    TRUE,
    '{"joggers_1.jpg"}',
    '{"joggers", "cargo", "streetwear", "unisex"}',
    '{"color":["Khaki","Black"], "size":["S","M","L","XL"]}'
),
-- --- Home & Kitchen (21-30) ---
(
    'Smart Coffee Maker with App Control',
    'Programmable coffee maker that can be controlled via smartphone app.',
    'Home & Kitchen',
    'Appliances',
    'HomeLux',
    'HL-CM-SMART',
    99.99,
    60,
    TRUE,
    '{"coffee_maker_1.jpg"}',
    '{"smart", "coffee", "appliance", "kitchen"}',
    '{}'
),
(
    'Bamboo Wood Cutting Board Set',
    'Set of 3 durable and eco-friendly bamboo cutting boards.',
    'Home & Kitchen',
    'Cookware',
    'EcoLiving',
    'EL-CB-BAM3',
    34.99,
    120,
    TRUE,
    '{"cutting_board_1.jpg"}',
    '{"bamboo", "kitchen", "eco-friendly", "set"}',
    '{}'
),
(
    'Aroma Diffuser Ultrasonic',
    'Ultrasonic essential oil diffuser with ambient LED light and auto shut-off.',
    'Home & Kitchen',
    'Decor',
    'ScentCo',
    'SC-AD-ULTRA',
    25.00,
    150,
    TRUE,
    '{"diffuser_1.jpg"}',
    '{"aroma", "diffuser", "essential-oil", "home-decor"}',
    '{"color":["White","Wood Grain"]}'
),
(
    'Plush Faux Fur Throw Blanket',
    'Incredibly soft and warm throw blanket for sofa or bed.',
    'Home & Kitchen',
    'Bedding',
    'CozyHome',
    'CH-TB-PLUSH',
    59.99,
    80,
    TRUE,
    '{"blanket_1.jpg"}',
    '{"throw", "fur", "plush", "winter"}',
    '{"color":["Cream","Grey","Navy"]}'
),
(
    'Stainless Steel Cookware Set (12-Piece)',
    'Professional grade stainless steel set with glass lids.',
    'Home & Kitchen',
    'Cookware',
    'ChefPro',
    'CP-CS-12P',
    199.00,
    40,
    TRUE,
    '{"cookware_1.jpg"}',
    '{"stainless-steel", "cookware", "set", "professional"}',
    '{}'
),
(
    'Abstract Canvas Wall Art',
    'Large abstract painting on canvas, ready to hang.',
    'Home & Kitchen',
    'Decor',
    'ArtVista',
    'AV-WA-ABST',
    75.50,
    30,
    TRUE,
    '{"wall_art_1.jpg"}',
    '{"canvas", "abstract", "wall-decor", "modern"}',
    '{"size":["Medium","Large"]}'
),
(
    'Memory Foam Pillow (Standard)',
    'Contour memory foam pillow for neck and back support.',
    'Home & Kitchen',
    'Bedding',
    'SleepPro',
    'SP-MF-PSTD',
    45.00,
    100,
    TRUE,
    '{"pillow_1.jpg"}',
    '{"memory-foam", "pillow", "sleep", "support"}',
    '{}'
),
(
    'Vintage Style Desk Lamp',
    'Metal desk lamp with adjustable arm and antique brass finish.',
    'Home & Kitchen',
    'Lighting',
    'Lumina',
    'LM-DL-VINT',
    69.99,
    70,
    TRUE,
    '{"lamp_1.jpg"}',
    '{"vintage", "desk-lamp", "brass", "lighting"}',
    '{}'
),
(
    'Handheld Vacuum Cleaner (Cordless)',
    'Lightweight and powerful cordless vacuum for quick cleanups.',
    'Home & Kitchen',
    'Appliances',
    'CleanSwift',
    'CS-VC-HHC',
    79.00,
    90,
    TRUE,
    '{"vacuum_1.jpg"}',
    '{"vacuum", "cordless", "cleaning", "handheld"}',
    '{}'
),
(
    'Ceramic Dinnerware Set (4 Place Settings)',
    'Elegant matte black ceramic set. Dishwasher safe.',
    'Home & Kitchen',
    'Tableware',
    'DineElegance',
    'DE-DS-C4P',
    89.00,
    50,
    TRUE,
    '{"dinnerware_1.jpg"}',
    '{"ceramic", "dinnerware", "matte", "set"}',
    '{"color":["Matte Black","Matte White"]}'
);